CREATE TABLE IF NOT EXISTS profile (
    email VARCHAR(100) PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    theme VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_profile_email ON profile(email);
